version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=psychoaibd
    volumes:
      - /home/postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - ./public:/app/public # Монтируем папку для статики
    ports:
      - "3020:3000"
    environment:
      - LLAMA_API_URL=92.252.240.206:11434
      - JWT_SECRET=nik852!!!A
      - JWT_REFRESH_SECRET=nik852!!!A
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/psychoaibd?schema=public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
