version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      # POSTGRES_PRISMA_URL: postgres://postgres:password@192.168.0.7:5432/learncup
      POSTGRES_PRISMA_URL: postgres://default:BLK6EPM7vOfa@ep-still-pond-a2zw1wye-pooler.eu-central-1.aws.neon.tech:5432/verceldb?sslmode=require&pgbouncer=true&connect_timeout=15