version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=psychoaibd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - ./public:/app/public # Монтируем папку для статики
    ports:
      - "3000:3000"
    environment:
      - LLAMA_API_URL="127.0.0.1:11434"
      - JWT_SECRET="your_secret_key"
      - JWT_REFRESH_SECRET="your_refresh_secret_key"
      - DATABASE_URL="postgresql://postgres:password@postgres:5433/psychoaibd?schema=public"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: psycho-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=nik852.nikita@mail.ru
      - PGADMIN_DEFAULT_PASWWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres
      
volumes:
  postgres_data:
    driver: local
