version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - LLAMA_API_URL="127.0.0.1:11434"
      - JWT_SECRET="your_secret_key"
      - JWT_REFRESH_SECRET="your_refresh_secret_key"
    extra_hosts:
      - "host.docker.internal:host-gateway"